#! /bin/sh
#
# $Id: $
#
# Copyright (c) 1997 Enterprise Systems Management Corp.
#
# This file is part of UName*It.
#
# UName*It is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# UName*It is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with UName*It; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

# This script will configure the unameit software after it has been installed.
# It sources the raw wrapper in order to set up its own running environment.
#
die() {
    echo $1 1>&2
    exit 1
}

## Parse args
[ $# -ne 1 ] && die "Usage: $0 UName*It_dir"
UNAMEIT=$1
[ ! -r $UNAMEIT/install/wrapper.sh ] && \
    die "Cannot find $UNAMEIT/install/wrapper.sh"

cd $UNAMEIT

## Create new wrapper. This script is only run on SunOS 4.X (the client only).
## Solaris and HP/UX use installation scripts when the packages are added.
cat > bin/unameit <<EOF
#! /bin/sh
UNAMEIT=$UNAMEIT; export UNAMEIT
UNAMEIT_ETC=/etc/unameit; export UNAMEIT_ETC
EOF
    cat install/wrapper.sh >> bin/unameit
    cat >> bin/unameit <<'EOF'
exec "`dirname $0`/exe/`basename $0`" "$@"
EOF
chmod 755 bin/unameit

for dir in bin sbin lbin lsbin; do
    ## Make links
    for f in $dir/exe/*; do
	if [ -x $f ]; then
	    basename=`basename $f`
	    if [ $f != bin/exe/unameit ]; then
	        rm -f $dir/$basename
	        ln bin/unameit $dir/$basename
	    fi
	    echo "Adding wrapper for $basename"
	fi
    done
done

exit 0
