#! /bin/sh
#
# $Id: $
#
# Copyright (c) 1997 Enterprise Systems Management Corp.
#
# This file is part of UName*It.
#
# UName*It is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# UName*It is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with UName*It; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

# Create a database using information from the configuration files.
#
# Start up TCL with this file as input.
# TCL treats the following line as a continuation of this comment \
exec tcl -n "$0" "$@"

package require Config
proc gc {param} {
    global unameitConfig
    unameit_config_ne unameitConfig $param unisqlx
}

unameit_getconfig unameitConfig unameitd

# set environment for unisqlx
unameit_configure_unisqlx unameitConfig

set CHECK [unameit_filename UNAMEIT_UNISQLX utilities spacedb_sa]
set DB_NAME [gc dbname]

if {[catch {exec $CHECK $DB_NAME >@stdout 2>@stderr}]} {
    puts stderr "Database does not exist or is not usable."
    exit 1
}

exit 0
