#!/bin/sh -e
#
# $Id: $
#
# Copyright (c) 1997 Enterprise Systems Management Corp.
#
# This file is part of UName*It.
#
# UName*It is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# UName*It is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with UName*It; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

dir=${1:?'please supply name of data directory to be created'}
shift

version=`cat $UNAMEIT_DATA/data/data.version`
datadir=$UNAMEIT_DATA/data/data.$version

if [ ! -r $datadir ]
then
    echo "$datadir is not readable"
    exit 1
fi

echo "copying data from $datadir into $dir"
exec $UNAMEIT/bin/unameitcl $UNAMEIT_SCRIPTS/dat_to_heap.tcl -c $datadir -d $dir "$@"
