#! /bin/bash
# $Id: $
#
# Copyright (c) 1997 Enterprise Systems Management Corp.
#
# This file is part of UName*It.
#
# UName*It is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# UName*It is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with UName*It; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

PATH=/bin:/usr/sbin:/opt/gnu/bin

die() {
    echo $1 1>&2; exit 1
}
usage() {
    die "Usage: $0 [-v] version"
}

verbose=
while getopts ":v" opt; do
    case $opt in
        v)
	    verbose=-v
	    ;;
        \?)
	    usage
	    ;;
    esac
done
shift $(($OPTIND-1))
[ $# -ne 1 ] && usage

version=$(echo $1 | sed 's/\./_/g')
[ ! -d /opt/cd/$version ] && die "Cannot find directory /opt/cd/$version"

cd /opt/cd

author="Enterprise Systems Management Corp.
14742 Newport Ave., Suite 207, 
Tustin, CA 92680 

+1 (714) 505-7686"

mkisofs -A "UName*It $version distribution" \
-o /opt/cd/$version.iso \
-P "$author" -p "$author" \
-r -T $verbose \
-V UNameIt /opt/cd/$version


