#! /bin/bash
# $Id: $
#
# Copyright (c) 1997 Enterprise Systems Management Corp.
#
# This file is part of UName*It.
#
# UName*It is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# UName*It is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with UName*It; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

# Makes symbolic links from the parts listed in the parts list. The symbolic
# links are put in lib. Also makes links from lbin/exe and lsbin/exe
# directories to the executables in the parts list (relatively through
# the new symbolic links just created).
. /opt/cd/common.sh

print_usage()
{
    echo "Usage: $0 UName*It_dir parts_file" 1>&2; exit 1
}

## Parse arguments
if [ $# != 2 ]; then
    print_usage
fi

unameit_dir=$1
parts_file=$2

## Check that there is a lib directory
if [ ! -d $unameit_dir/lib ]; then
    echo "$unameit_dir/lib doesn't exist or is not a directory" 1>&2; exit 1
fi

## Read parts file and check its integrity
. $parts_file
check_parts_integrity

## Check whether the directories exist. If they are symlinks, just delete
## and relink them. If they are directories, delete them if the -d option
## was given, otherwise complain.
cd $unameit_dir
mkdir -p lbin/exe lsbin/exe
for part in tcl krb5 unisqlx; do
    if [ -e lib/$part ]; then
	if [ -L lib/$part ]; then
	    rm lib/$part
	elif [ -d lib/$part ]; then
	    rm -rf lib/$part
	else
	    echo "File $unameit_dir/lib/$part is of the incorrect type" 1>&2
	    exit 1
        fi
    fi

    partdir=/opt/$(eval echo \$$part)
    ln -s $partdir lib/$part

    ## Make symlinks in the lbin and lsbin directories to the real executables
    ## using relative paths through the symlink set up above.
    for bindir in bin sbin; do
        for fullexe in $partdir/$bindir/*; do
	    # If the shell matches nothing, then you will get something like
	    # "/opt/tcl/bin/*" and we must skip the file name in this case.
	    # Stupid Bourne shell behavior.
	    if [ ! -e $fullexe ]; then
		continue
	    fi
            if [ -x $fullexe ]; then
		shortname=${fullexe##/*/}
		rm -f l$bindir/exe/$shortname
		ln -s ../../lib/$part/$bindir/$shortname \
		    l$bindir/exe/$shortname
	    fi
	done
    done
done
exit 0
